mqtt:
    address: 10.3.1.199:1883
    password: public
    user: admin
fms:
    host: 10.1.100.3
    services:
        - name: area
          address: http://10.1.205.3:8888
product:
    description: awesome fms daemon CLI program.
    name: chaos
    uuid: 93a25ee9-0f08-4398-a0e4-72aa28ee1ebf
    version: 1.0.0
